-- \c serenity

INSERT INTO services(experience_id, service_name, description, allergens, duration, price)
VALUES(1, 'Restorative Yoga', 'Restorative yoga is a form of yoga that seeks to achieve physical, mental and emotional relaxation with the aid of props. The use of props makes it easier for you to maintain balance while you are stimulating and relaxing your body.', '', 60, 40),
(1, 'Meditation', 'Meditation describes a state of consciousness where the mind is free from scattered thoughts and various habitual patterns. When you participate in meditation all the activity of the mind is reduced and you begin to uncover something more! At Serenity, classes include:  a short seated warm up to prepare the body to sit and breathing techniques to clear and calm the mind.', '', 60, 40),
(1, 'Yin Yoga', 'Yin yoga is a slow-paced style of yoga with postures, or asanas, that are held for longer periods of time—for beginners, it may range from 45 seconds to two minutes; more advanced practitioners may stay in one asana for five minutes or more.', '', 60, 40),
(2, 'Fountain of Youth', 'Our Fountain of Youth Facials include products and techniques designed to slow the aging process, brighten skin, and reduce wrinkles. If you long for a more youthful complexion, select from our variety of anti-aging facial treatments ranging from vitamin-infused serums to light therapy facials to microdermabrasion.', '', 50, 80),
(2, 'Wellness', 'This signature facial offers the best skin restoration experience. It includes all the best a facial can give; a thorough cleanse and skin analysis followed with a deep pore lifting Enzyme mask, relaxing face massage, Lip Smoothing and Eye Renewal treatment masks, as well as a specially-blended customized facial mask to complete your wellness facial. We’ll even massage your feet before slipping them into warm booties and give you a blissful Shea Butter hand massage.', 'Shea Butter', 50, 80),
(2, 'Glow', 'This facial uses a mask of pure 24-karat gold. Gold not only gives us beautiful, glowing and youthful skin but it also slows down collagen depletion, increases skin elasticity, lightens complexion, stimulates cells to firm skin, improves blood circulation and prevents premature aging and wrinkles. The gold facial also assists in lymphatic drainage and improved blood circulation, while helping to enhance skin elasticity.', '', 60, 85),
(3, 'Pure Relaxation', 'This massage incorporates long, circulatory strokes and flow to enhance the traditional Swedish massage while restoring calm to the mind and body. Aromatherapy of your choice is added to the service to amplify your experience', 'Lavender', 90, 120),
(3, 'Deep Tissue', 'This massage penetrates the deepest layers of tense muscle to relieve aches and provide physical benefits to those areas needing additional attention. Our targeted approach to alleviating pain is perfect for athletes and those needing to soothe pressure points.', '', 90, 120),
(3, 'Shiatsu', 'By applying ancient Eastern techniques, this massage provides essential therapeutic benefits. Our therapists apply sustained, measured pressure to points along the bodies meridian.', '', 80, 135),
(4, 'Rain Room', 'Take in the sounds and smells of the rain forest in our signature Serenity Rain Room.   Become immersed in the aromas of scented flowers, tropical air produced by the built-in sauna, and the sounds of the rain as you quiet the heart and mind from the stresses of the day. Elements of mist and rain  are designed to promote deep relaxation and renewal of vital energies while a soothing steam bath relaxes muscles, cleanses skin and helps to remove toxins. Inhalation of eucalyptus also enhances relaxation.', 'eucalyptus', 30, 0),
(4, 'Sauna', 'Sweating is a great way to burn calories and rid your body of unwanted toxins. Saunas help your body release a number of toxins as well as relieve unwanted pain, increase your circulation, and purify your skin. Serenity offers 4-minute sessions at 160-180 degrees, slowly working your way up to 15- to 30-minute sessions.', '', 30, 0),
(4, 'Hot Tub', 'Warm water, or “hydro” therapy can promote relaxation, pain relief while improving sleep habits. The heat and massage work together to clear your mind, reduce stress and soothe overworked muscles. At Serenity, we have 12 private hot tubs for you to enjoy. Book one today and start your journey towards inner peace.', '', 30, 0),
(4, 'Saltwater Pool', 'By eliminating the harsh chemicals found in most pools, our salt water amenity provides a natural body of water in which to relax. Water is known to have myriad restorative properties. By cleansing the water with  organic salt, our pool is not only clean but provides additional bouyancy that removes pressure from your joints.', '', 30, 0);

SELECT * FROM services;
